# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true
    http_client:
        scoped_clients:
            slack.client:
                base_uri: '%env(SLACK_BOT_WEBHOOK_URL)%'
                headers:
                    Accept: 'application/json; charset=utf-8'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
