framework:
  webhook:
    routing:
      stripe:
        service: App\Webhook\StripeRequestParser
        secret: '%env(STRIPE_WEBHOOK_SECRET)%'
      stripetest:
        service: App\Webhook\StripeRequestParser
        secret: '%env(STRIPE_WEBHOOK_SECRET_TESTMODE)%'