framework:
  webhook:
    routing:
      stripe:
        service: App\Webhook\StripeRequestParser
        secret: '%env(STRIPE_HT2_LIVEMODE_WEBHOOK_SECRET)%'
      stripetest:
        service: App\Webhook\StripeRequestParser
        secret: '%env(STRIPE_HT2_TESTMODE_WEBHOOK_SECRET)%'     
      stripe1:
        service: App\Webhook\StripeRequestParser
        secret: '%env(STRIPE_HT1_LIVEMODE_WEBHOOK_SECRET)%'
      stripe1test:
        service: App\Webhook\StripeRequestParser
        secret: '%env(STRIPE_HT1_TESTMODE_WEBHOOK_SECRET)%'