---
ht1_intramed_testmode:
  HT_API_BASEURL: HEALTHTRAIN_IT_API_BASEURL
  HT_API_CLIENT_ID: HEALTHTRAIN_IT_INTRAMED_CLIENT_ID
  HT_API_CLIENT_SECRET: HEALTHTRAIN_IT_INTRAMED_CLIENT_SECRET
  STRIPE_SECRET_KEY: STRIPE_HT1_TESTMODE_SECRET_KEY
  STRIPE_BILLING_URL: STRIPE_HT1_TESTMODE_BILLING_URL

ht2_spotonmedics_testmode:
  HT_API_BASEURL: HEALTHTRAIN_IT_API_BASEURL
  HT_API_CLIENT_ID: HEALTHTRAIN_IT_SOM_CLIENT_ID
  HT_API_CLIENT_SECRET: HEALTHTRAIN_IT_SOM_CLIENT_SECRET
  STRIPE_SECRET_KEY: STRIPE_HT2_TESTMODE_SECRET_KEY
  STRIPE_BILLING_URL: STRIPE_HT2_TESTMODE_BILLING_URL

ht1_livemode:
  STRIPE_SECRET_KEY: STRIPE_HT1_LIVEMODE_SECRET_KEY
  STRIPE_BILLING_URL: STRIPE_HT1_LIVEMODE_BILLING_URL

ht2_livemode:
  STRIPE_SECRET_KEY: STRIPE_HT2_LIVEMODE_SECRET_KEY
  STRIPE_BILLING_URL: STRIPE_HT2_LIVEMODE_BILLING_URL

ht1_testmode:
  STRIPE_SECRET_KEY: STRIPE_HT1_TESTMODE_SECRET_KEY
  STRIPE_BILLING_URL: STRIPE_HT1_TESTMODE_BILLING_URL

ht2_testmode:
  STRIPE_SECRET_KEY: STRIPE_HT2_TESTMODE_SECRET_KEY
  STRIPE_BILLING_URL: STRIPE_HT2_TESTMODE_BILLING_URL
