---
spotonmedics:
  livemode:
    config: ht2_livemode
    identifier: HealthTrain SOM
    testmode: false
    products:
      htp_live_pCiBce4AF6XXzH2mn:
        healthtrain:
          organisationOnboarding: false
        stripe:
          priceId: price_1QZaG0AU7J6SUXutWSzBW6WD
          paymentMethods: pmc_1QNGRLAU7J6SUXutucJVChnS
        mailplus:
          automationId: bc0a8795-536c-432b-83ef-bcb46944eb0f
  testmode:
    config: ht2_spotonmedics_testmode
    identifier: HealthTrain SOM Testmode
    testmode: true
    products:
      htp_test_H8oYvathg6fv4XF2u:
        healthtrain:
          organisationOnboarding: true
        stripe:
          priceId: price_1QD4l5AU7J6SUXutqQV2xIkg
          paymentMethods: pmc_1QFP2jAU7J6SUXutnqqCXyO3
        mailplus:
          automationId: 61fa1a1c-ba87-484d-8890-39868d538989

intramed-pilot:
  livemode:
    config: ht1_livemode
    identifier: HealthTrain Intramed Pilot
    testmode: false
    products:
      htp_live_g8pyaCarYzqGHcQYUpwY:
          healthtrain:
            organisationOnboarding: false
          stripe:
            priceId: "price_1R4sG2CQZsgE0X5Z3CQWDN2C"
            paymentMethods: "pmc_1R7GRgCQZsgE0X5ZQE4nyBKx"
          mailplus: false
  testmode:
    config: ht1_intramed_testmode
    identifier: HealthTrain Intramed Pilot Testmode
    testmode: false
    products:
      htp_test_3hZ4hzPBCsmsXLmjTebZ:
        healthtrain:
          organisationOnboarding: false
        stripe:
          priceId: price_1R4IF2CQZsgE0X5Z6zqadeFe
          paymentMethods: pmc_1R7GSICQZsgE0X5Z4JZnXcKr
        mailplus: false

standalone:
  livemode:
    config: ht2_livemode
    identifier: HealthTrain Standalone
    testmode: false
    products:
      htp_live_yXq6sCHEKvHfAYkrqWCv:
        healthtrain:
          organisationOnboarding: false
        stripe:
          priceId: price_1R1YziAU7J6SUXuteXP3MBRG
          paymentMethods: pmc_1QNGRLAU7J6SUXutucJVChnS
        mailplus: false
  testmode:
    config: ht2_testmode
    identifier: HealthTrain Standalone Testmode
    testmode: true
    products:
      htp_test_yXq6sCHEKvHfAYkrqWCv:
        healthtrain:
          organisationOnboarding: false
        stripe:
          priceId: price_1R1ZeBAU7J6SUXutGcxZcf2H
          paymentMethods: pmc_1QFP2jAU7J6SUXutnqqCXyO3
        mailplus: false

hwo:
  livemode:
    config: ht2_livemode
    identifier: Huiswerkoefeningen.nl
    testmode: false
    products:
      hwo_live_syK2z4Y9Qz8VQYraA:
        healthtrain:
          organisationOnboarding: false
        stripe:
          priceId: price_1QgnqxAU7J6SUXut3qZzE0KU
          paymentMethods: pmc_1QNGRLAU7J6SUXutucJVChnS
        mailplus: false
  testmode:
    config: ht2_testmode
    identifier: Huiswerkoefeningen.nl Testmode
    testmode: true
    products:
      hwo_test_syK2z4Y9Qz8VQYraA:
        healthtrain:
          organisationOnboarding: false
        stripe:
          priceId: price_1Qgn0bAU7J6SUXutnjXsDfIF
          paymentMethods: pmc_1QFP2jAU7J6SUXutnqqCXyO3
        mailplus: false
