controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

checkout_plans_index:
    path: /
    controller: App\Controller\CheckoutController::index
    methods: GET
    host: "checkout.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

checkout_plans:
    path: /plans/{plan}
    controller: App\Controller\CheckoutController::plans
    methods: GET
    host: "checkout.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

checkout_portal:
    path: /portal
    controller: App\Controller\CheckoutController::portal_redirect
    methods: GET
    host: "checkout.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

# checkout_portal_login:
#     path: /portal/customer
#     controller: App\Controller\CheckoutController::portal_redirect_login
#     methods: POST
#     host: "checkout.{domain}"
#     defaults:
#         domain: '%domain%'
#     requirements:
#         domain: '%domain%'

checkout_create_session:
    path: /session/create
    controller: App\Controller\CheckoutController::create_session
    methods: POST
    host: "checkout.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

checkout_create_session_success:
    path: /session/success/{checkout_session_id}
    controller: App\Controller\CheckoutController::session_success
    methods: GET
    host: "checkout.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

checkout_create_session_cancelled:
    path: /session/cancelled
    controller: App\Controller\CheckoutController::session_cancelled
    methods: GET
    host: "checkout.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

video_tools_embed:
    path: /tools/embed/
    controller: App\Controller\VideosController::tools_embed
    methods: GET|HEAD
    host: "videos.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

video_embed_sproutvideo:
    path: /embed/sv/{video_id}/{key_id}/
    controller: App\Controller\VideosController::embed_sproutvideo
    methods: GET|HEAD
    host: "videos.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

invite_ht_prod:
    path: /i/{invitationId}/{userOrganisationConnectionId}/
    controller: App\Controller\InviteController::invite_ht_prod
    methods: GET|HEAD
    host: "{subdomain}.{domain}"
    defaults:
        domain: '%domain%'
        subdomain: "invite"
    requirements:
        subdomain: "invite|i"
        domain: "%domain%"

invite_ht_at:
    path: /ht_at/{invitationId}/{userOrganisationConnectionId}/
    controller: App\Controller\InviteController::invite_ht_at
    methods: GET|HEAD
    host: "{subdomain}.{domain}"
    defaults:
        domain: '%domain%'
        subdomain: "invite"
    requirements:
        subdomain: "invite|i"
        domain: "%domain%"

invite_ht_it:
    path: /ht_it/{invitationId}/{userOrganisationConnectionId}/
    controller: App\Controller\InviteController::invite_ht_it
    methods: GET|HEAD
    host: "{subdomain}.{domain}"
    defaults:
        domain: '%domain%'
        subdomain: "invite"
    requirements:
        subdomain: "invite|i"
        domain: "%domain%"

invite_htger_prod:
    path: /ig/{invitationId}/{userOrganisationConnectionId}/
    controller: App\Controller\InviteController::invite_htger_prod
    methods: GET|HEAD
    host: "{subdomain}.{domain}"
    defaults:
        domain: '%domain%'
        subdomain: "invite"
    requirements:
        subdomain: "invite|i"
        domain: "%domain%"

invite_htger_prod_legacy:
    path: /Invite/{invitationId}/{userOrganisationConnectionId}/
    controller: App\Controller\InviteController::invite_htger_prod
    methods: GET|HEAD
    host: "{subdomain}.{domain}"
    defaults:
        domain: '%domain%'
        subdomain: "invite"
    requirements:
        subdomain: "invite|i"
        domain: "%domain%"

invite_htger_at:
    path: /htger_at/{invitationId}/{userOrganisationConnectionId}/
    controller: App\Controller\InviteController::invite_htger_at
    methods: GET|HEAD
    host: "{subdomain}.{domain}"
    defaults:
        domain: '%domain%'
        subdomain: "invite"
    requirements:
        subdomain: "invite|i"
        domain: "%domain%"

webhooks:
    resource: '@FrameworkBundle/Resources/config/routing/webhook.xml'
    prefix: /webhooks/

# test_slack:
#     path: /test/slack
#     controller: App\Controller\DefaultController::slackTest
#     methods: GET|HEAD

# test_stripe:
#     path: /test/stripe
#     controller: App\Controller\DefaultController::stripeTest
#     methods: GET|HEAD

index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: GET|HEAD
