---
# EPD config: Intramed
- lookup_key: epd_intramed_001
  name: epd_intramed_001
  metadata:
    ClientDetailsDeeplinkAvailable: unavailable
    ClientDetailsDeeplinkEnabled: false
    EPDType: Intramed
    ProductName: "HealthTrain Platform i.c.m. Intramed Compleet"
    ViewAllClientsEnabled: true

# EPD config: SpotOnMedics FysioOne
- lookup_key: epd_spotonmedics_001
  name: epd_spotonmedics_001
  metadata:
    ClientDetailsDeeplinkAvailable: unavailable
    ClientDetailsDeeplinkEnabled: false
    EPDType: SpotOnMedics
    ProductName: "HealthTrain Platform i.c.m. SpotOnMedics FysioOne"
    ViewAllClientsEnabled: true

# EPD config: Fysiomanager
- lookup_key: epd_fysiomanager_001
  name: epd_fysiomanager_001
  metadata:
    ClientDetailsDeeplinkAvailable: available
    ClientDetailsDeeplinkEnabled: true
    EPDType: Fysiomanager
    ProductName: "HealthTrain Platform i.c.m. Fysiomanager"
    ViewAllClientsEnabled: true

# EPD config: Flux
- lookup_key: epd_flux_001
  name: epd_flux_001
  metadata:
    ClientDetailsDeeplinkAvailable: available
    ClientDetailsDeeplinkEnabled: true
    EPDType: Flux
    ProductName: "HealthTrain Platform i.c.m. flux"
    ViewAllClientsEnabled: true

# EPD config: Standalone
- lookup_key: epd_standalone_001
  name: epd_standalone_001
  metadata:
    ClientDetailsDeeplinkAvailable: available
    ClientDetailsDeeplinkEnabled: false
    EPDType: StandAlone
    ProductName: "HealthTrain Platform Standalone"
    ViewAllClientsEnabled: true

# Module: Activity tracking
- lookup_key: module_activity_upsell_001
  name: module_activity_upsell_001
  metadata:
    ActivityTrackingAvailable: upsell
- lookup_key: module_activity_available_001
  name: module_activity_available_001
  metadata:
    ActivityTrackingAvailable: available
- lookup_key: module_activity_unavailable_001
  name: module_activity_unavailable_001
  metadata:
    ActivityTrackingAvailable: unavailable

# Module: Appointments
- lookup_key: module_appointments_upsell_001
  name: module_appoint_upsell_001
  metadata:
    AppointmentsAvailable: upsell
- lookup_key: module_appointments_available_001
  name: module_appoint_available_001
  metadata:
    AppointmentsAvailable: available
- lookup_key: module_appointments_unavailable_001
  name: module_appoint_unavailable_001
  metadata:
    AppointmentsAvailable: unavailable

# Module: Invites
- lookup_key: module_invite_users_epd_001
  name: module_invite_users_epd_001
  metadata:
    CreateClientEnabled: false
    CreateTherapistsEnabled: false
- lookup_key: module_invite_users_sso_001
  name: module_invite_users_sso_001
  metadata:
    CreateClientEnabled: false
    CreateTherapistsEnabled: true
- lookup_key: module_invite_users_manual_001
  name: module_invite_users_manual_001
  metadata:
    CreateClientEnabled: true
    CreateTherapistsEnabled: true

# Module: Messages
- lookup_key: module_messages_upsell_001
  name: module_messages_upsell_001
  metadata:
    MessagesAvailable: upsell
- lookup_key: module_messages_available_001
  name: module_messages_available_001
  metadata:
    MessagesAvailable: available
- lookup_key: module_messages_unavailable_001
  name: module_messages_unavailable_001
  metadata:
    MessagesAvailable: unavailable

# Module: Notifications
- lookup_key: module_notifications_upsell_001
  name: module_notific_upsell_001
  metadata:
    AppointConfirmAvailable: upsell
    AppointConfirmChannelOptions: None,Push
    AppointRemindAvailable: upsell
    AppointRemindChannelOptions: None,Push
    NotificationsAvailable: upsell
- lookup_key: module_notifications_confirmations_001
  name: module_notific_upsell_001
  metadata:
    AppointConfirmAvailable: available
    AppointConfirmChannelOptions: None,Push,PushMail
    AppointRemindAvailable: upsell
    AppointRemindChannelOptions: None,Push
    NotificationsAvailable: available
- lookup_key: module_notifications_unavailable_001
  name: module_notific_unavailable_001
  metadata:
    AppointConfirmAvailable: unavailable
    AppointConfirmChannelOptions: None,Push
    AppointRemindAvailable: unavailable
    AppointRemindChannelOptions: None,Push
    NotificationsAvailable: unavailable
- lookup_key: module_notifications_pushmail_001
  name: module_notific_pushmail_001
  metadata:
    AppointConfirmAvailable: available
    AppointConfirmChannelOptions: None,Push,PushMail
    AppointRemindAvailable: available
    AppointRemindChannelOptions: None,Push,PushMail
    NotificationsAvailable: available
- lookup_key: module_notifications_pushmailsms_001
  name: module_notific_pushmailsms_001
  metadata:
    AppointConfirmAvailable: available
    AppointConfirmChannelOptions: None,Push,PushMail,PushMailSMS
    AppointRemindAvailable: available
    AppointRemindChannelOptions: None,Push,PushMail,PushMailSMS
    NotificationsAvailable: available

# Module: Protocols
- lookup_key: module_protocols_upsell_001
  name: module_protocols_upsell_001
  metadata:
    ProtocolsAvailable: upsell
- lookup_key: module_protocols_unavailable_001
  name: module_protocols_unavailable_001
  metadata:
    ProtocolsAvailable: unavailable
- lookup_key: module_protocols_available_001
  name: module_protocols_available_001
  metadata:
    ProtocolsAvailable: available
    
# Module: Videocalls
- lookup_key: module_videocalls_upsell_001
  name: module_videocalls_upsell_001
  metadata:
    VideocallsAvailable: upsell
- lookup_key: module_videocalls_unavailable_001
  name: module_videocalls_unavailable_001
  metadata:
    VideocallsAvailable: unavailable
- lookup_key: module_videocalls_available_001
  name: module_videocalls_available_001
  metadata:
    VideocallsAvailable: available